# version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #   env_file:
  #     - ./frontend/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"